### ISSUE TITLE
userAdded, userRemoved could not work correctly

### ISSUE THREAD

**Issue by maruTA-bis5** [maruTA-bis5/hubot-matteruser#3]
チャンネルにメンバーが追加されたとき(userAdded)とメンバーが削除されたとき(userRemoved)に、以下のエラーが発生する。
```
[Wed Nov 23 2016 15:09:42 GMT+0900 (JST)] ERROR TypeError: Cannot read property 'toString' of undefined
  at new User (/home/maruyama/timeline-bot/node_modules/hubot/src/user.coffee:9:19, <js>:14:46)
  at Brain.userForId (/home/maruyama/timeline-bot/node_modules/hubot/src/brain.coffee:106:7, <js>:93:16)
  at Matteruser.userRemoved (/home/maruyama/timeline-bot/node_modules/hubot-matteruser/src/matteruser.coffee:153:16, <js>:230:31)
  at Client.<anonymous> (/home/maruyama/timeline-bot/node_modules/hubot-matteruser/src/matteruser.coffee:1:1, <js>:3:61)
  at emitOne (events.js:96:13)
  at Client.emit (events.js:188:7)
  at Client.onMessage (/home/maruyama/timeline-bot/node_modules/mattermost-client/src/client.coffee:214:17, <js>:285:23)
  at WebSocket.<anonymous> (/home/maruyama/timeline-bot/node_modules/mattermost-client/src/client.coffee:158:13, <js>:217:22)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
```
Mattermost 3.5でWebSocketのメッセージが変わっているようで、実際にuserAdded/userRemovedに渡されるオブジェクトは以下の内容となっている。

- userAdded
```
{ event: 'user_added',
  data:
   { team_id: '4y6g1x1qrtntfb3h9txc39izuc',
     user_id: 'ebab4zfq6ib67cw6sbw1xjscsr' },
  broadcast:
   { omit_users: null,
     user_id: '',
     channel_id: 'z3f76r76niyomqygn3ba7m4p8c',
     team_id: '' } }
```
- userRemoved
```
{ event: 'user_removed',
  data:
   { channel_id: 'z3f76r76niyomqygn3ba7m4p8c',
     remover_id: 'zk3dueusj7n8uqbhuzcuww1fkr' },
  broadcast:
   { omit_users: null,
     user_id: 'ebab4zfq6ib67cw6sbw1xjscsr',
     channel_id: '',
     team_id: '' } }
```

いずれの処理もbrain.userForIdに渡しているのは`msg.userId(=undefined)`なので、適切に直してやる必要がある。

**Comment by maruTA-bis5** [comment]
よく見たら`data.remover_id`って削除操作をした人か。`broadcast.user_id`が削除されたメンバーだが、これそのまま使ってもよいものなのか?

**Comment by maruTA-bis5** [comment]
`user_id`, `remover_id`のメッセージと、`channel_id`, `remover_id`のメッセージが飛んでるみたい。後者は無視するのがベター?
```go
	message := model.NewWebSocketEvent(model.WEBSOCKET_EVENT_USER_REMOVED, "", channel.Id, "", nil)
	message.Add("user_id", userIdToRemove)
	message.Add("remover_id", removerUserId)
	go Publish(message)

	// because the removed user no longer belongs to the channel we need to send a separate websocket event
	userMsg := model.NewWebSocketEvent(model.WEBSOCKET_EVENT_USER_REMOVED, "", "", userIdToRemove, nil)
	userMsg.Add("channel_id", channel.Id)
	userMsg.Add("remover_id", removerUserId)
	go Publish(userMsg)
```
https://github.com/mattermost/platform/blob/master/api/channel.go#L1125

**Comment by maruTA-bis5** [comment]
後者の場合は自身が削除されているのか。

**Comment by maruTA-bis5** [comment]
ああ、だから`broadcast.user_id`がセットされるのね。後者なら自身が削除されたとして処理すれば良さそうだ。

**Comment by maruTA-bis5** [comment]
本体が直っているので終わり
